export default {
  tm7: {
    'Text Field0': 'writtenAt',
    'Text Field1': 'documentDay',
    'Text Field2': 'documentMonth',
    'Text Field3': 'documentYear',
    'Text Field4': 'surname',
    'Text Field5': 'firstName',
    'Text Field6': 'middleName',
    'Text Field7': 'volunteerAge',
    'Text Field8': 'birthDate',
    'Text Field9': 'birthMonth',
    'Text Field10': 'birthYear',
    'Text Field11': 'placeOfBirth',
    'Text Field12': 'volunteerNationality',
    'Text Field13': 'passportNumber',
    'Text Field14': 'passportIssueDay',
    'Text Field15': 'passportIssueMonth',
    'Text Field16': 'passportExpiryMonth',
    'Text Field17': 'passportIssueYear',
    'Text Field18': 'passportExpiryYear',
    'Text Field19': 'passportIssuedAt',
    'Text Field20': 'passportExpiryDay',
    'Text Field21': 'visaType',
    'Text Field22': 'arrivedBy',
    'Text Field23': 'arrivedFrom',
    'Text Field24': 'arrivedPort',
    'Text Field25': 'arrivedDate',
    'Text Field26': 'arrivedMonth',
    'Text Field27': 'arrivedYear',
    'Text Field28': 'tm6Number',
    'Text Field29': 'extensionDays',
    'Text Field30': 'extensionReason',
    'Text Field31': 'extensionReason1',
    'Text Field32': 'extensionReason2',
    'Text Field33': 'extensionReason3',
    'Text Field34': 'addressInThailand',
    'Text Field35': 'volunteerFullName',
    'Text Field36': 'addressNumber',
    'Text Field37': 'addressRoad',
    'Text Field38': 'addressSubdistrict',
    'Text Field39': 'addressDistrict',
    'Text Field40': 'addressProvince',
  },

  ost: {
    ชื่อองค์การ: 'orgNameThai',
    'Name of Agenjcy in English': 'orgNameEnglish',
    'Tel of Agency': 'orgTel',
    'curo@tutamail.com': 'orgEmail',
    'Agency Register No': 'orgRegisterNo',
    'The Mai Activiaties of Agency': 'orgActivities',
    "Volunteer's Highest Education": 'educationLevel',
    "Volunteer's Name of Institution Country": 'educationInstitutionAndCountry',
    "Volunteer's Year Fraduated": 'educationGraduatedYear',
    "Volunteer's Address in Thailand": 'addressInThailand',
    "Volunteer's Tellephone Number": 'volunteerPhoneNumber',
    "Volunteer's Email address": 'volunteerEmail',
    'Passport No': 'passportNumber',
    'Date of Issue': 'passportIssueDate',
    'Visa class': 'visaType',
    ออกให้วันที่: 'visaIssueDate',
    li1lJJ: 'visaIssuedAt',
    ชื่อโครงการ: 'projectName',
    'Starting date': 'projectStartDate',
    'Job Description2': 'projectPositionDescription2',
    'Name of Head of Agency': 'orgHeadName',
    'Nationality of Agency': 'orgHeadNationality',
    Age: 'orgHeadAge',
    'Address of Agency': 'orgAddress',
    'Agency Registered by': 'orgRegisteredBy',
    'Agency Date of Issue': 'orgRegisteredDate',
    "Volunteer's Name": 'volunteerFullName',
    "Volunteer's Nationality": 'volunteerNationality',
    "Volunteer's Race": 'volunteerRace',
    "Volunteer's Age": 'volunteerAge',
    "Volunteer's Date of Birth": 'volunteerDateOfBirth',
    "Volunteer's Marriage status": 'volunteerMaritalStatus',
    'Issued at': 'passportIssuedAt',
    ต่ออายุถึงวันที่: 'visaExpiryDate',
    ตำแหน่ง: 'projectPosition',
    Text18: 'projectPlaceOfWork',
    ระยะเวลาที่ปฏิบัติบัติงาน: 'projectDuration',
    'Job Description1': 'projectPositionDescription1',
    "Volunteer's Sex": 'volunteerGender',
    "Volunteer's Home Country": 'volunteerHomeCountry',
    'Expiry Date': 'passportExpiryDate',
    'Name of Volunteer': 'volunteerFullName',
    'Name of Organization': 'orgNameEnglish',
    'Head of Agency': 'orgHeadName',
    วันที่: 'documentDay',
    เดือน: 'documentMonth',
    'พ.ศ': 'documentYear',
  },

  foundationCharter: null,
  foundationMap: null,
  foundationOfficePictures: null,
  foundationTax: null,
  houseBook: null,
} as const;
